services:
  db:
    image: mysql:8.0 # lub mariadb:10.11 jeśli używasz MariaDB
    container_name: projekt_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titus_simbasket
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - '3306:3306' # lokalny port:port kontenera
    volumes:
      - db_data:/var/lib/mysql # dane persystentne
      - ./docker/init:/docker-entrypoint-initdb.d # auto-import przy pierwszym starcie

volumes:
  db_data:
